#!/usr/bin/env bash
# installs nginx and configures it on a remote server
# using the following configurations

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
