#!/usr/bin/env bash
# This script stops the process started by
# 4-to_infinity_and_beyond if it is running

[ -n "$(pgrep -f "4-to_infinity_and_beyond")" ] &&
    kill "$(pgrep -f "4-to_infinity_and_beyond")" &&
    echo "Terminated" || echo "Process not found"

# kill "$(pgrep -f 4-to_infinity_and_beyond)"
