#!/usr/bin/env bash
# This script kills the process 7-highlander

# Find the process ID (PID) of the "7-highlander" process
pid=$(pgrep -f "7-highlander")

kill -9 "$pid"
# kill -9 $(pgrep -f "7-highlander")
# pkill -f -SIGKILL 7-highlander
