#!/usr/bin/env bash
# This script displays username, user id, and home
# directory path for each user in /etc/passwd

# Using a while loop to read each line in /etc/passwd
while read -r password; do
    echo "$password" | cut -d ":" -f1,3,6
done < "/etc/passwd"
