#!/usr/bin/env bash
# This script tells the story of the /etc/passwd file using a while loop + IFS.

# Using a while loop to read each line in /etc/passwd
while IFS=':' read -r username x uid gid gecos homedir shell; do
    echo "The user $username is part of the $gid gang, "\
	 "lives in $homedir and rides $shell. "\
	 "$uid's place is protected by the passcode $x, "\
	 "more info about the user here: $gecos"
done < "/etc/passwd"
