#!/usr/bin/env bash
# This script configures an Ubuntu server to change
# the IP for localhost and facebook.com

cp /etc/hosts ~/hosts.new

# Change localhost IP to 127.0.0.2
echo "127.0.0.2	      localhost" > ~/hosts.new

# Change facebook.com IP to 8.8.8.8
echo "8.8.8.8	      	 facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts